### ISSUE TITLE
Problem reading data from RefSeq

### ISSUE THREAD

**Issue by pirale** [gtonkinhill/panaroo#206] opened 2022-10-21 20:33 UTC
Hi there,

I've been having problems trying to use panaroo with data from RefSeq. I've tried listing .gbffs in a file or listing .gffs tab .fastas in a file and I both times get a similar error. After executing
` panaroo -i test.tsv -o $basis/results/panaroo/ --remove-invalid-genes -a pan -t 20 --clean-mode strict`
I get an error message:

`Error reading prokka input!
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 622, in _populate_from_lines
    self._insert(f, c)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 566, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.IntegrityError: UNIQUE constraint failed: features.id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_##gff-version 3

[gff file got printed here out here, I abbridge]
...skipping...
worker
    r = call_item()
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 289, in __call__
    for func, args, kwargs in self.items]
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 289, in <listcomp>
    for func, args, kwargs in self.items]
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 136, in get_gene_sequences
    from_string=True)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 1401, in create_db
    c.create()
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 543, in create
    self._populate_from_lines(self.iterator)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 624, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/gffutils/create.py", line 257, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID cds-WP_096252754.1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 272, in process_prokka_input
    for gff_no, gff in job)
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File ".../miniconda/envs/panaroo/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File ".../miniconda/envs/panaroo/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: Duplicate ID cds-WP_096252754.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../miniconda/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/panaroo/__main__.py", line 300, in main
    args.n_cpu, args.table)

  File ".../miniconda/envs/panaroo/lib/python3.7/site-packages/panaroo/prokka.py", line 282, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
`

I attach the input files for your reference. Thank you very much for your support.
[panaroo.tar.gz](https://github.com/gtonkinhill/panaroo/files/9842268/panaroo.tar.gz)

**Comment by gtonkinhill** [comment] 2022-10-27 03:36
Hi,

Sorry for the delay in getting back to you. Which version of Panaroo are you running?
I tried your example on the latest version (v1.3) and it seemed to run okay.

**Comment by pirale** [comment] 2022-11-01 21:13
Hi @gtonkinhill ,

Thank you for your response. I am running panaroo v. 1.3.0. Since I had upgraded from a previous version, I tried deleting the conda environment and then reinstalling from scratch, but to no avail. I'm still getting the same error message.

Thank you so much for your help.

**Comment by gtonkinhill** [comment] 2022-12-12 06:33
Unfortunately, I have been unable to reproduce this issue. I am closing it for now but will reopen it if someone runs into a similar problem.

**Closed by gtonkinhill** 2022-12-12 06:33 UTC

**Comment by nashanghenzan** [comment] 2023-05-13 14:20
> Unfortunately, I have been unable to reproduce this issue. I am closing it for now but will reopen it if someone runs into a similar problem.

recently i have the same issue when i use panaroo 1.3.3, the `--remove-invalid-genes` seems don't work when i add gff file from refseq, the detail:
```
(panaroo) [root@centos7-02-66b664b9d9-gz85w prokka]# panaroo -i SHR_bin.0.fa/*.gff TSR_bin.28.fa/*.gff PSR_bin.7.fa/*.gff GCF_000368625.1/*.gff \
> -o /mnt/semibin/panaroo/Acinetobacter_schindleri --clean-mode strict -t 15 --remove-invalid-genes
pre-processing gff3 files...
  0%|                                                                                                            | 0/1 [00:00<?, ?it/s]Problem reading GFF3 file:  GCF_000368625.1/Acinetobacter_schindleri.gff
  0%|                                                                                                            | 0/1 [00:04<?, ?it/s]
Error reading prokka input!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 127, in get_gene_sequences
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 278, in process_prokka_input
    gene_sequence_list = Parallel(n_jobs=n_cpu)(
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/root/miniconda3/envs/panaroo/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/root/miniconda3/envs/panaroo/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: Error reading prokka input!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 312, in main
    process_prokka_input(args.input_files, args.output_dir,
  File "/root/miniconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 290, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
```

**Comment by nashanghenzan** [comment] 2023-05-14 12:50
> Unfortunately, I have been unable to reproduce this issue. I am closing it for now but will reopen it if someone runs into a similar problem.

i found that the refseq gff3 file don't have sequence info , so i decide to annotate refseq fasta file by prokka.(another mathod may convert gbff to gff?)
