### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython.

### ISSUE THREAD

**Issue by mabouelk** [gtonkinhill/panaroo#181] opened 2022-07-24 04:56 UTC
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by gtonkinhill** [comment] 2022-08-04 07:18
Hi,

Can you confirm which version of Panaroo you are running? I believe this should be fixed in the latest version.

**Comment by mabouelk** [comment] 2022-08-04 14:34
I am using V1.2.10

**Comment by gtonkinhill** [comment] 2022-08-09 10:51
Hi,

Sorry for the delay in getting back to you. I have not been able to reproduce this issue. Would you be able to send though which command you're running and the version of python and BioPython you are using?

**Comment by naturepoker** [comment] 2022-10-12 21:14
Hi, 

I'm actually having this very same issue as well - trying to run panaroo on Ubuntu 22.04, installed just today using mamba in its own environment.

```
conda create -n panaroo
conda activate panaroo
mamba install -c conda-forge -c bioconda -c defaults panaroo 
```

Running something like below command:

`panaroo -i ../../../gff/*.gff -o panaroo_comp --clean-mode strict -a core --aligner clustal -t 8`

Results in below error message:

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/panaroo/bin/panaroo", line 6, in <module>
    from panaroo.__main__ import main
  File "/home/user/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/__main__.py", line 14, in <module>
    from .generate_output import *
  File "/home/user/miniconda3/envs/panaroo/lib/python3.10/site-packages/panaroo/generate_output.py", line 10, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/user/.local/lib/python3.10/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
Biopython version in the environment is 1.79
It does look like Panaroo on bioconda is version 1.1.2 

Let me know if I can provide you with more info. 

Thank you!

**Comment by gtonkinhill** [comment] 2022-10-12 22:32
Hi,

Can you double-check the version of python that is installed?  I'm not sure what causes this as the bioconda tests complete successfully and I am not able to reproduce it on my system. 

My guess might be that it is something to do with what is installed in your base conda environment but I am not sure.

**Comment by naturepoker** [comment] 2022-10-13 22:23
Hi, 

Thanks for responding. 

I've only ever installed panaroo in dedicated conda environments and never in base, or alongside any other packages - just a heads up since that sounds pretty important for trouble shooting!

Base conda python version is 3.10.6, ditto for dedicated panaroo environment.

I went back and deleted the environment, emptied out conda cache and tried to install panaroo in dedicated conda environment again, just in case (I'm using mamba here for actual installation, by the way). 

Same issue - the process pulls panaroo version 1.1.2 for some reason. 
 
![Screenshot from 2022-10-13 18-06-05](https://user-images.githubusercontent.com/48851179/195719982-73d65161-8953-4e1b-a239-d1bc08e181bf.png)

The machine is running Ubuntu LTS 22.04 with latest updates.


I got a little curious so went to another machine and tried installing panaroo again using the same process, this one's a laptop running Ubuntu 20.04.05 LTS. Despite using the exact same process, panaroo installs fine on this machine... It pulls the latest 1.3.0 without any problem. Base conda python version here is 3.9.5, so it's actually a little behind. What's even more curious, after the working panaroo installation on the laptop, python version in the panaroo environment is lowered to 3.7.12.

I'm not sure if there's anything you can do here... Documenting in detail just in case anyone else runs into the same issue.  

Thank you!

**Comment by gtonkinhill** [comment] 2022-10-13 23:04
Hi @naturepoker,

Thanks for looking into this so carefully. I've re-opened the issue so that it is easier for others to find. 
I'll try and see if I can work out what is causing this. I am wondering if it is a particular combination of python packages that causes it to downgrade panaroo. 

In the meantime, you might have better success installing the python part of panaroo using pip with

```
pip3 install git+https://github.com/gtonkinhill/panaroo
```

**Comment by NatureGate** [comment] 2022-11-25 12:48
I met the same problem , I resolved it by conda install -c bioconda  panaroo=3.10,but then another method appeared 

running cmd: cd-hit -T 6 -i results/combined_protein_CDS.fasta -o results/combined_protein_cdhit_out.txt -c 0.98 -s 0.98 -aL 0.0 -AL 99999999 -aS 0.0 -AS 99999999 -M 0 -d 999 -g 1 -n 2
generating initial network...
Traceback (most recent call last):
  File "/home/longrui/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/longrui/miniconda3/envs/panaroo/lib/python3.6/site-packages/panaroo/__main__.py", line 319, in main
    all_dna=args.all_seq_in_graph)
  File "/home/longrui/miniconda3/envs/panaroo/lib/python3.6/site-packages/panaroo/generate_network.py", line 76, in generate_network
    if prev is not None: G.nodes[prev]['hasEnd'] = True
TypeError: 'method' object is not subscriptable

**Comment by NatureGate** [comment] 2022-11-25 13:02
> 

can you show your python version and all the needed package version?

**Comment by NatureGate** [comment] 2022-11-25 13:38
just now ,I resolved that problem.

ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the molecule_type as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
**the problem above maybe the version of your python is 2.7**
conda install python=3.8
conda install -c bioconda panaroo=1.3.0
then I finished the pangenome analysis job ! 
good luck

**Comment by iagosblancos** [comment] 2023-02-01 19:15
Hello, I have faced the same problem. I realized that this version of Panaroo which I had was downloaded from Anaconda 3. When I uninstalled that and replaced for Miniconda, this message did not return to appear.

**Comment by gtonkinhill** [comment] 2023-02-01 23:21
Thanks very much for posting your solution!

**Closed** 2023-02-28 03:13 UTC
Labels: help wanted
