### ISSUE TITLE
Edges in the graph are not updated with refound genes

### ISSUE THREAD

**Issue by hdore** [gtonkinhill/panaroo#141] opened 2021-12-03 18:56 UTC
Hello,

Thank you for developing panaroo, it's great to have a tool to explore the pangenome as a graph!

I was exploring a graph made from 16 whole bacterial genomes and I'm having troubles interpreting some of the graph features.

In the example below, the 3 highlighted nodes all have a size of 16, with a single copy of each of these genes in each genome of my dataset. So I don't understand how there can be 2 paths going from galE to group_1247 (galE>1247 and galE>3811>1247).

![image](https://user-images.githubusercontent.com/50923770/144657035-f2e0d6d1-b888-466b-9ddb-90409de93622.png)

Thank you for your help,

hdore

**Comment by hdore** [comment] 2021-12-03 19:15
Hello,
I think I found a possible explanation: one of the genes in group_3811 is a refound gene. The edge galE>1247 is supported by only 1 genome, which corresponds to the genome with the refound gene.
Thus it seems that the edges in the graph are not updated with the refound genes. Is there a reason behind this? I find it quite misleading, in particular when looking at potential structural variants, since we are loosing the power of genes refinding from Panaroo.

Best,

hdore

**Comment by gtonkinhill** [comment] 2021-12-09 00:13
Hi,

Yes, currently the edges are not updated to reflect refound genes. This is a bug (originally reported in #83) that I'm hoping to fix in future versions. It does not impact on the building of the graph and presence/absence matrices but can make interpretation more difficult. I will try and patch this soon.

**Comment by gtonkinhill** [comment] 2021-12-09 00:14
I will close this as it is a duplicate of #83 but will try get to it soon.

**Closed by gtonkinhill** 2021-12-09 00:14 UTC
