### ISSUE TITLE
Some problem about panaroo's result

### ISSUE THREAD

**Issue by Bin-Ma** [gtonkinhill/panaroo#255] opened 2023-11-07 13:19 UTC
Hi @pansapiens,

I used the panaroo to construct the bacterial pangenome. If I select the '--codons' parameter, it will go wrong with the genes can't divisible by 3. Then, I removed the parameter and tried to aligned with codon by myself. However, the length of aligned gene generated by panaroo was not a multiple of 3.

I have no idea about how to solve this problem. Looking forward to your reply!

Bin

**Comment by nzmacalasdair** [comment] 2023-11-07 14:31
Hello! 

Thanks for getting in touch about this, glad to hear that the codon alignment module is getting some use!

This is definitely not expected behaviour, as there are checks in the codon alignment code which should identify when DNA sequences are not alignable at the protein level, and default back to nucleotide-level alignment.

Would it be possible for you to share the error message panaroo returns when you've been running it with the --codons flag?

Thanks!

**Comment by Bin-Ma** [comment] 2023-11-08 08:52
Thanks for your rapid response, @nzmacalasdair !
The following is the error message with the command `panaroo -i ./gff/* -o panaroo_result_test  -t 40 --clean-mode strict -a pan --remove-invalid-gene --codons`. By the way, my panaroo version is 1.3.4.

`/home/mabin_epi/anaconda3/envs/roary/lib/python3.7/site-packages/Bio/Seq.py:2742: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning,
Traceback (most recent call last):
  File "/home/mabin_epi/anaconda3/envs/roary/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/mabin_epi/anaconda3/envs/roary/lib/python3.7/site-packages/panaroo/__main__.py", line 506, in main
    args.alr, args.codons, isolate_names)
  File "/home/mabin_epi/anaconda3/envs/roary/lib/python3.7/site-packages/panaroo/generate_output.py", line 303, in generate_pan_genome_alignment
    threads)
  File "/home/mabin_epi/anaconda3/envs/roary/lib/python3.7/site-packages/panaroo/generate_alignments.py", line 435, in reverse_translate_sequences
    alignment = codonalign.build(clean_proteins[index], clean_dna[index])
  File "/home/mabin_epi/anaconda3/envs/roary/lib/python3.7/site-packages/Bio/codonalign/__init__.py", line 90, in build
    "a *PROTEIN* alignment, found %r" % pro.seq.alphabet
TypeError: Alphabet Error!
The input alignment should be a *PROTEIN* alignment, found SingleLetterAlphabet()`

Looking forward to your reply!

Bin

**Comment by Bin-Ma** [comment] 2023-11-09 15:20
Hi @nzmacalasdair !
Thank you very much for your professional suggestion. Now, it works successfully.
Besides, there are other two error message occurred in other datasets as follow. The command is `nohup panaroo -i ./gff/* -o panaroo_result  -t 60 --clean-mode strict -a pan --remove-invalid-gene &`.

First error message (72 bacterial genome):

<img width="1823" alt="截屏2023-11-09 23 17 26" src="https://github.com/gtonkinhill/panaroo/assets/80092539/d1e369ce-2f29-4425-a96d-556eb573d2ad">

Second error message (166 bacterial genome):

<img width="1605" alt="截屏2023-11-09 23 19 00" src="https://github.com/gtonkinhill/panaroo/assets/80092539/466673de-cd20-4648-a742-59c072036ac5">

Thanks again for your kindly help. Looking forward to your reply.

Bin

**Comment by nzmacalasdair** [comment] 2023-11-09 18:13
Hi,

I've never seen errors like this before, and it is difficult to for me to definitively diagnose these errors without the input data, as I think there is probably something usual going on there. I'm not sure theses two errors are actually are the same issue, either, but here are some ideas:

1. An issue with the `--remove-invalid-gene` flag. Could you run it without this flag (particularly on the 166 genomes) and let me know what issues you encounter (if any?) 
2. Something unexpected in your input data. In the case of the first error message, it almost looks like panaroo could not find any core genes -- are the 72 bacterial genomes very distantly related? In the second case, it looks like there is an issue with the 639th gene on the first contig in isolate 23 -- you can check the `gene_data.csv` file to see is there is anything unusual about this gene, the geneid in gene_data should be 23_0_640. Are the 72 and 166 isolate sets completed disjoint, ie there are no overlapping isolates between them?
3. Are all the other dependencies up to date in the conda environment you are trying to run panaroo in? It might particularly be worth checking if numpy is up to date.

**Comment by gtonkinhill** [comment] 2024-02-23 15:00
This may have been caused by collisions occurring with temporary files being created in the TMPDIR system directory by python and the package gffutils. This has been addressed in v1.4. 

I'll close this issue for now and re-open it if someone observes the same problem in the latest version.

**Closed by gtonkinhill** 2024-02-23 15:00 UTC
