### ISSUE TITLE
Error when generating initial network

### ISSUE THREAD

**Issue by zakisaati** [gtonkinhill/panaroo#64] opened 2020-06-27 10:03 UTC
Hi there,
I am running Panaroo over 4404 bacterial genomes. For that, I executed the following command:
panaroo -i *.gff -o ./panaroo_results/ --core_threshold 0.99 -t 6 --clean-mode strict

The first step was succesfully performed, I think, but it gave me a failure. Here I copy and paste the failure together with some of the previous steps:

(........)
100.0%---------- new table with       38 representatives
 comparing sequences from   25869654  to   25870634
.......... 25870000  finished    2472850  clusters
---------- new table with      290 representatives

 25870634  finished    2473043  clusters

Approximated maximum memory consumption: 12395M
writing new database
writing clustering information
program completed !

Total CPU time 953563.94
generating initial network...
Traceback (most recent call last):
  File "/home/zaki/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/zaki/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/__main__.py", line 292, in main
    all_dna=args.all_seq_in_graph)
  File "/home/zaki/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/generate_network.py", line 180, in generate_network
    cluster_centroid_data[current_cluster]
KeyError: 977040

The version installed is v1.2.2 (conda installation) and python 3.7.6.

At that moment, some output files seems to be correctly generated:
(...)panaroo_results$ ls
combined_DNA_CDS.fasta  combined_protein_cdhit_out.txt  combined_protein_cdhit_out.txt.clstr  combined_protein_CDS.fasta  gene_data.csv  tmpc4f20ij0

Note: the folder "tmpc4f20ij0" is empty

Could you please give me some advice to overcome this problem? Thank you very much in advance

**Comment by gtonkinhill** [comment] 2020-06-27 11:41
This could be due to a very short gene in one of your datasets. The initial clustering stage can fail if a gene is less than 10aa in length. Unfortunately we have not yet added a more informative error message here. You should be able to check if this is the case by looking at the lengths of the sequences in `combined_protein_CDS.fasta`

If this doesn't resolve your issue it would be helpful if you were able to narrow down the problem to a smaller example set which we could use to debug the issue.

**Comment by zakisaati** [comment] 2020-06-28 07:53
Thank you for your help. I checked it, and I do not have any protein less than 10aa. The smallest is 29aa.
I have tried with a smaller dataset, 5 genomes, and it worked fine, till the end. Could it be related with a RAM issue? I do not know if the step to generate the initial network requires higher RAM...

**Comment by zakisaati** [comment] 2020-06-29 20:43
I am not sure if I do understand the combined_protein_cdhit_out.txt.clstr file, but here could be the problem. 
The file "combined_protein_CDS.fasta" have 25870634 sequences
The file "combined_protein_cdhit_out.txt.clstr" have 2473043 "clusters"
Just in case, I counted also the sequences of the file "combined_protein_cdhit_out.txt" and it have the same amount, 2473043. 

Is that what you asked for? I am not sure about how to check if all the genes from one file are present in the other one, but, since the "combined_protein_CDS.fasta" file have 10 times more sequences than the "combined_protein_cdhit_out.txt", I guess that only some of them are represented there.

I do not have problems to share the files privately, if needed

Thank you again

**Comment by gtonkinhill** [comment] 2020-06-30 18:14
Hmm, it might be easier if I take a quick look at the files. If you are able to send me the `combined_protein_CDS.fasta`, `combined_protein_cdhit_out.txt.clstr`, `combined_protein_cdhit_out.txt` and `gene_data.csv` files I should be able to work out what's going on. I'm not sure what the easiest way to share the files is but my email is gqt20@cam.ac.uk so that we can work it out.

**Comment by gtonkinhill** [comment] 2020-07-03 13:47
It looks like this issue was caused by comma's in either the file or contig names. I will attempt to remove such commas in the next release.

**Comment by gtonkinhill** [comment] 2020-08-05 22:57
This should be fixed in the latest release (1.2.3)

**Closed by gtonkinhill** 2020-08-05 22:57 UTC
Labels: bug
