### ISSUE TITLE
gene name

### ISSUE THREAD

**Issue by Biofarmer** [gtonkinhill/panaroo#174] opened 2022-06-14 09:14 UTC
Hi,
I am using panaroo v1.2.10, and have some questions about the output:
1. what's meaning of "~~~" in the gene_presence_absence table, such as "afuB_1~~~afuB~~~afuB_2"?
2. when I set the --core_threshold 0.90, why the (soft) core gene in "summary_statistics" file is still showing >95%? Is the gene present in core_gene_alignment.aln present 90% of sample or 95%?

Thanks

**Comment by nzmacalasdair** [comment] 2022-06-15 11:55
Hi Biofarmer!

When panaroo joins two annotations from different genomes in the pan-genome analysis, it uses "~~~" as a separator. So in the case of your example, the single pangenome gene was variously annotated as afuB, afub_1, and afuB_2. 

The summary_statistics file is invariant to the core_threshold option, as the latter is used only for generating the core alignment. This is a legacy behaviour which causes some confusion (ie #157 #116 ) so we may consider changing this in the future, but for now this discrepancy between the thresholds used in the summary_statistics file and the core genome alignment.

**Comment by Biofarmer** [comment] 2022-06-15 11:59
> Hi Biofarmer!
> 
> When panaroo joins two annotations from different genomes in the pan-genome analysis, it uses "~~~" as a separator. So in the case of your example, the single pangenome gene was variously annotated as afuB, afub_1, and afuB_2 in the different input GFF files.
> 
> The summary_statistics file is invariant to the core_threshold option, as the latter is used only for generating the core alignment. This is a legacy behaviour which causes some confusion (ie #157 #116 ) so we may consider changing this in the future, but for now there is this discrepancy between the thresholds used in the summary_statistics file and the core genome alignment.

Thanks, so the --core_threshold is assured to be used for any others files that are related to core genes, right?

**Comment by nzmacalasdair** [comment] 2022-06-15 12:09
Yes, that should be the case

**Comment by Biofarmer** [comment] 2022-06-15 12:48
> Yes, that should be the case

Thanks

**Comment by Biofarmer** [comment] 2022-06-20 12:11
Hi, when translating the pan_genome_reference.fa from panaroo into proteins, there is warning "/anaconda3/lib/python3.9/site-packages/Bio/Seq.py:2979: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(". May I ask why? This warning can be ignored or what should I do? Is the result of panaroo fine? There is no error reported from running panaroo.

**Comment by gtonkinhill** [comment] 2022-06-21 21:19
Hi, 

This might be caused by your script truncating the gene sequence. It is probably worth manually checking a few of the sequences to make sure it is behaving as you expect.

**Comment by Biofarmer** [comment] 2022-06-23 08:42
Thanks, I may change to another script. In addition, when I repeated to run panaroo for 2000 genomes, the gene number in each category of "summary_statistics.txt" was slightly different, but very small (like total genes 25100 vs. 25132). May I ask there is a random process in panaroo or any other reasons?

**Comment by Biofarmer** [comment] 2022-06-23 08:42
Thanks, I may change to another script. In addition, when I repeated to run panaroo for 2000 genomes, the gene number in each category of "summary_statistics.txt" was slightly different, but very small (like total genes 25100 vs. 25132). May I ask there is a random process in panaroo or any other reasons?

**Comment by gtonkinhill** [comment] 2022-08-10 09:04
Hi,

Sorry, I missed this initially. We have had reports of this before but we were unable to reproduce the behaviour. We did suspect it was a version issue with one of Panaroo's dependencies. If you are able to create a small reproducible example that would be very helpful in working out what is causing this.

**Comment by gtonkinhill** [comment] 2022-08-22 12:29
I'm closing this for now as the issue is documented in #134

**Closed as completed by gtonkinhill** 2022-08-22 12:29 UTC
