### ISSUE TITLE
Alternative start codon GTG translated as Val instead of Met

### ISSUE THREAD

**Issue by cednotsed** [gtonkinhill/panaroo#274] opened 2024-03-14 23:10 UTC
I compared the sequences obtained through panaroo-extract-gene with and without the --dna flag. I noticed that in some cases, genes starting with the GTG alternative start codon are translated as valine instead of methionine, perhaps due to the usage of an incorrect translation table. 

The panaroo output files (v1.3.4) were generated without the `--codon-table` flag (Ref #53), so according to the help message the default translation table should be 11. Specifying `--codon-table 11` results in the same behaviour. May I know what is the reason for this discrepancy?

Thanks in advance.

**Comment by gtonkinhill** [comment] 2024-03-26 05:52
Hi,

Apologies for the slow response. Is this occurring at the start of the gene? 
I think this may be caused by the translation function failing to take into account different start codons properly.

**Comment by gtonkinhill** [comment] 2024-03-26 06:38
Just re-read the title! Yes, I think this is an issue with the start codon translation as Biopython does not seem to take it into account. I'll look at fixing this for the next release.

**Comment by gtonkinhill** [comment] 2024-04-03 08:08
This should hopefully be fixed in the latest release. Thanks very much for reporting the issue.

**Closed by gtonkinhill** 2024-04-03 08:08 UTC

**Comment by cednotsed** [comment] 2024-04-03 08:10
Thanks to you for resolving this so quickly!

**Comment by iqbal-lab** [comment] 2024-04-03 09:20
cc @Danderson123
