### ISSUE TITLE
Re turned non-zero exit status 1.

### ISSUE THREAD

**Issue by MHassanSaeed** [gtonkinhill/panaroo#247] opened 2023-08-26 13:06 UTC
The following appears after running panaroo (it's near completion) but ended up here.

Please let me know what's the issue.

Thanks.

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 358, in main
    G = collapse_families(G,
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/clean_network.py", line 113, in collapse_families
    cdhit_clusters = iterative_cdhit(G,
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/cdhit.py", line 411, in iterative_cdhit
    run_cdhit_est(input_file=temp_input_file.name,
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/cdhit.py", line 147, in run_cdhit_est
    subprocess.run(cmd, shell=True, check=True)
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd-hit-est -T 1 -i /home/ubuntu/Ent Cohorts/Prokfaecalis/fgff/results/tmp947rw3gg/tmp6buvv3ld -o /home/ubuntu/Ent Cohorts/Prokfaecalis/fgff/results/tmp947rw3gg/tmpwtaf8w45 -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7 > /dev/null' returned non-zero exit status 1.

**Comment by gtonkinhill** [comment] 2023-08-28 05:51
Hi,

It's tricky to diagnose this issue from the error message. If you run the cd-hit command that crashed separately it should print out a more detailed error message. In this case you would run

```
cd-hit-est -T 1 -i /home/ubuntu/Ent Cohorts/Prokfaecalis/fgff/results/tmp947rw3gg/tmp6buvv3ld -o /home/ubuntu/Ent Cohorts/Prokfaecalis/fgff/results/tmp947rw3gg/tmpwtaf8w45 -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7
```

**Comment by MHassanSaeed** [comment] 2023-08-28 10:39
Hi,

I tried running it but unfortunately couldn't useful information.

It just gives cd-hit usage options.

**Comment by gtonkinhill** [comment] 2023-09-06 07:54
Hi, 

Sorry for the slow reply. My guess is that something has gone wrong with the cd-hit installation. 

You could try re-installing Panaroo in a fresh conda environment and making sure `cd-hit-est` runs successfully on a DNA fasta file before trying Panaroo again.

**Comment by MHassanSaeed** [comment] 2023-09-07 13:11
Hi,

Thank you for your response. `cd-hit-est `runs successfully but Panaroo comes with the same error again even after reinstalling Panaroo in a fresh conda environment.

**Comment by gtonkinhill** [comment] 2023-09-08 02:20
Hi,

That's strange. To debug it further it would be helpful if you could send a small reproducible example including the files used (or a subset that reproduces the problem) and the command you ran.

**Comment by MHassanSaeed** [comment] 2023-09-08 09:55
Hi,

I have sent you an email.

**Comment by MHassanSaeed** [comment] 2023-09-19 13:42
Hi,

Have you managed to debug the error?

**Comment by gtonkinhill** [comment] 2023-09-21 02:56
Apologies for the delay, I've just sent you an email.

**Comment by chahatupreti** [comment] 2023-10-25 19:37
Hi,
I just did a new install of panaroo and am getting the same error. Could you please provide a solution?

**Comment by gtonkinhill** [comment] 2023-10-26 05:49
I'll close this and answer in the new issue raised by @chahatupreti. The previous issue could not be reproduced using the supplied files and was likely due to an installation problem.

**Closed by gtonkinhill** 2023-10-26 05:49 UTC
