### ISSUE TITLE
Core genome aligned sequences does not equal number of core genes

### ISSUE THREAD

**Issue by kneubehl** [gtonkinhill/panaroo#93] opened 2020-12-17 06:38 UTC
I ran panaroo with the mafft aligner for core genes and noticed a discrepancy in the number of core genes output by the summary_statistics.txt file vs the number of genes aligned in the aligned_gene_sequences folder. Summary_stats.txt indicate 951 core genes but only 835 genes were aligned in the the aligned_gene_sequences folder. I ran panaroo with the following commands: panaroo -i *.gff -o output --clean-mode strict --remove-invalid-genes --min_trailing_support 0 --trailing_recursive 0 -a core --aligner mafft -t 30 --merge_paralogs --threshold 0.8  (I ran with the parameters we had talked about in prior issues/questions because Borrelia genomes are weird). Any insight would be helpful.

**Comment by kneubehl** [comment] 2020-12-20 01:57
Looking more into this, the 835 seems right because if I look at the gene_presence_absence.Rtab file there are 835 genes that are present in all the strains being analyzed. There are also 835 genes that are a aligned in the concatenated multi-sequence alignment for the core genome. This appears to be an issue of counting then in the summary_stats.txt file. Using roary_plot.py the pie-chart it does show that the core genome is indeed 835. Interesting.

**Comment by gtonkinhill** [comment] 2021-01-11 10:33
Hi apologies for being slow on this. I have had to focus on finishing my thesis and aim to get back to panaroo development in late January.

**Comment by kneubehl** [comment] 2021-01-11 17:31
Good luck!


Regards,


Alex Kneubehl

PhD Candidate

Laboratory of Dr. Job Lopez
Vector Biology and Bacterial Pathogens Lab

Department of Pediatrics

National School of Tropical Medicine at
Baylor College of Medicine

Twitter: @AlexKneubehl




________________________________

**Comment by gtonkinhill** [comment] 2021-01-26 00:57
Hi,

Sorry about the wait. I think this could be in part due to Panaroo excluding additional copies of paralogous gene families when performing the multiple sequence alignment. This is done as having multiple copies of the same gene in the pangenome reference can cause issues with alignment.

I've also realised that `summary_stats.txt` uses ≤ 0.95 while the core alignments uses <0.95 by default. I will update the code to make these consistent in the next release. 

@marade if you generate the alignments using the `-a pan` option does it recover the missing alignments?

@kneubehl this may be part of your problem but I am unsure why you would see the discrepancy between the `summary_stats.txt` file and `gene_presence_absence.Rtab`. Would it be possible to share the `summary_stats.txt`, `gene_presence_absence.Rtab` and `final_graph.gml` files to help identify the issue?

**Comment by gtonkinhill** [comment] 2021-02-09 22:47
The discrepancy between `summary_stats.txt` and `gene_presence_absence.Rtab` was caused by an off by one error in a reference to an array that led the counts in `summary_stats.txt` to incorrectly count gene fragments rather than gene clusters. This has been fixed in 88ea7d994ecef5810848a99b7d9b16e12d0b3a3e

**Closed by gtonkinhill** 2021-02-09 22:47 UTC
