### ISSUE TITLE
Protein sequence missing from file extracted with panaroo-extract-gene

### ISSUE THREAD

**Issue by andreaniml** [gtonkinhill/panaroo#194] opened 2022-09-10 19:01 UTC
Hi!

After generating the pangenome with panaroo I've noticed that there is one sequence missing from the protein sequences when I extract them using the panaroo-extract-gene command if I compare it with the "Gene.aln.fas" from the aligned_gene_sequences folder. Is the same genome missing in both genes that I've looked into (Eg I have 171 protein sequences in one file, but 172 sequences in the nucleotide alignment)

The protein sequence that's missing is not a duplicate and its cds is not interrupted by any stop codons.

The gene_presence absence Rtab accounts for the missing protein so does the roary-like table, I can find the protein if I search the locus tag in the gene_data.csv file

I think I can extract the missing sequence from the  gene_data.csv, but I wanted to know if this is a bug or expected behavior and the missing protein sequence is dropped for a reason

Many thanks!

**Comment by gtonkinhill** [comment] 2022-09-12 00:15
Hi,

Thanks for flagging this. I think this was caused by a bug in the script that led to gene fragments that had been merged being skipped. 

These appear as 'ID_1;ID_2' in the`gene_presence_absence.csv` file.

I have added a fix in e5608f3 which I will merge into the main branch when the tests have passed. In the mean time you can install the updated version using pip

```
pip install git+https://github.com/gtonkinhill/panaroo@devel
```

**Comment by andreaniml** [comment] 2022-09-13 05:40
Hi
I installed panaroo using pip and ran it again, however the problem persists (and I think the panaroo extract genes script has lost the function --idtype).

The gene and genome appear when I try to use the panaroo-gene-neighbourhood script, is just the sequence extraction that seems to be working incorrectly.

**Comment by gtonkinhill** [comment] 2022-09-13 07:18
Hi,

I mistakenly made the changes in an old version. That will teach me to generate updates at the end of the day!
I have now taken a look at the latest version and am having trouble reproducing your issue. Would it be possible to send a small example that reproduces the problem?

**Comment by gtonkinhill** [comment] 2022-09-15 02:07
Hi,

Thanks very much for sending through the files. It turned out it was an off by one error which caused the first genome to be skipped. This should now be fixed in the devel branch.

Please let me know if you find that the update still hasn't resolved the problem and thanks for your help in diagnosing the issue.

**Comment by andreaniml** [comment] 2022-09-15 18:31
Just tried using the extract script after installing the devel option, everything is working fine! 
There is no need to run the pangenome analysis again, right?

Thank you for such a fast fix!

**Comment by gtonkinhill** [comment] 2022-09-15 23:34
Great, and yes there you don't need to rerun the main pipeline.

**Closed by gtonkinhill** 2022-09-15 23:34 UTC
Labels: bug
